name: tug
description: A tug-of-war style value alignment tracker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  
  # Routing
  go_router: ^14.8.0
  
  # Firebase
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_core_web: ^2.10.0
  firebase_auth_web: ^5.8.12
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2  # Added path_provider
  flutter_secure_storage: ^10.0.0-beta.4
  
  # UI Components
  fl_chart: ^0.70.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Utilities
  intl: ^0.20.2
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Development Tools
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  bloc_test: ^10.0.0
  mockito: ^5.4.3
  
  # Testing
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    # - assets/icons/
    # - assets/images/
    # - assets/fonts/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600