name: tug
description: Track your values and overcome your vices
publish_to: 'none'
version: 2.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  
  # Routing
  go_router: ^14.8.0
  
  # Firebase
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_core_web: ^2.10.0
  firebase_auth_web: ^5.8.12
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  firebase_ai: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  purchases_flutter: ^8.8.0
  
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2  # Added path_provider
  flutter_secure_storage: ^10.0.0-beta.4
  
  # UI Components
  fl_chart: ^0.70.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_slidable: ^3.0.1
  
  # Utilities
  intl: ^0.20.2
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.0.0
  font_awesome_flutter: ^10.6.0 
  shared_preferences: ^2.5.3
  confetti: ^0.8.0
  url_launcher: ^6.3.1 # For URL handling and deep links
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  image_picker: ^1.0.4

dependency_overrides:
  firebase_app_check: # Disable Firebase App Check
  firebase_app_check_platform_interface: # Disable Firebase App Check platform interface
  firebase_app_check_web: # Disable Firebase App Check web

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Development Tools
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  bloc_test: ^10.0.0
  mockito: ^5.4.3
  
  # Testing
  integration_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/images/tug_logo.png"
    background_color: "#6C38D4"
    theme_color: "#6C38D4"
  image_path: "assets/images/tug_logo.png"
  min_sdk_android: 21 # Android min sdk min:16, default 21
      
flutter:
  uses-material-design: true

  assets:
    - .env
    # - assets/icons/
    # - assets/images/
    # - assets/fonts/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600