global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@tug-app.com'
  smtp_auth_username: ''
  smtp_auth_password: ''

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://api:8000/monitoring/alerts/webhook'
    send_resolved: true

# Email notifications (configure with your SMTP settings)
- name: 'email'
  email_configs:
  - to: 'admin@tug-app.com'
    subject: 'TUG API Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Details: {{ range .Labels.SortedPairs }}{{ .Name }}: {{ .Value }}{{ end }}
      {{ end }}

# Slack notifications (configure with your webhook URL)
- name: 'slack'
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
    channel: '#alerts'
    title: 'TUG API Alert'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']