server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: tug-api-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: tug-api
      __path__: /var/log/tug/*.log

  pipeline_stages:
  - json:
      expressions:
        timestamp: '@timestamp'
        level: level
        message: message
        service: service
        logger: logger
        correlation_id: correlation_id
        user_id: user_id
        endpoint: endpoint
        method: method
        status_code: status_code
        response_time_ms: response_time_ms
        error_type: error_type

  - timestamp:
      source: timestamp
      format: RFC3339

  - labels:
      level:
      service:
      logger:
      method:
      endpoint:
      error_type: