version: '3.8'

services:
  api:
    build: .
    container_name: tug-api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DB_NAME=tug
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
    volumes:
      - .:/app
      # Add a volume mount for Firebase credentials
      - ${FIREBASE_CREDENTIALS_PATH}:/app/firebase-credentials.json:ro
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: tug-mongo
    ports:
      - "27017:27017"
    volumes:
      - tug_mongo_data:/data/db

volumes:
  tug_mongo_data: